name: project deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: 121.140.125.176
          username: test
          password: qwer1234
          port: 115
          script: |
            rm -rf ./cicd
            git clone https://github.com/atimaby28/cicd.git
            cd ./cicd
            chmod 755 ./gradlew
            ./gradlew bootJar
            docker rm -f back
            docker image prune -f
            docker build --tag hanwhabootcamp17/backend:latest .
            docker run -d --name back -p 8080:8080 hanwhabootcamp17/backend:latest

            
